#!/bin/bash
## Build GMD Table A1 (priors + posterior) as .docx from the table the POSTPROCESS wrote.
##
## ⭐ WHY IT EXISTS. `deliverables/GMD_TableA1_priors_posterior_L24.docx` (2026-09-19) is built on
## L24 and the paper ships L27 (Marcus, 09-24). The L24 table lists 58 parameters, NINE of which the
## shipped model does not sample (--cut-fastdyn, --fix-gamma, --no-d2-gsic, --no-ledger,
## --precip-reparam), and posterior columns move by up to several hundred percent between the two.
##
## ⚠ THE CONTENT IS NOT WRITTEN HERE. `python/ladrillo_prior_posterior_table.py` already emits
## outputs/ladrillo_prior_posterior_<TAG>.md as part of every arm's postprocess, priors taken from
## calibrate_mcmc_ext.jl --dump-priors (as SCORED, never transcribed). This script only converts.
## ⛔ Never hand-edit the .md: it is regenerated by the postprocess and an edit would be lost.
##
## ⚠ The L24 .docx is LEFT IN PLACE as provenance. This writes a NEW _L27 file; it does not
## overwrite, because a superseded deliverable still answers "what did the L24 draft say?".
##
## ⛔ .docx is written by PANDOC, never by hand and never with ElementTree (which renames namespace
## prefixes and makes Word report "unreadable content" — and the round-trip cannot see it). The
## build is then GATED by an INDEPENDENT READER (textutil, which is not pandoc), because a
## structurally broken .docx still unzips fine and still has a plausible byte size.
set -uo pipefail
cd "$(dirname "$0")"
TAG="${1:-L27}"
SRC="outputs/ladrillo_prior_posterior_${TAG}.md"
OUT="deliverables/GMD_TableA1_priors_posterior_${TAG}.docx"
say(){ echo "[$(date '+%m-%d %H:%M:%S')] $*"; }

[[ -f "$SRC" ]] || { say "MISSING $SRC — run python/ladrillo_prior_posterior_table.py --tag=$TAG first"; exit 2; }

## ⚠ PRESERVE-FIRST GATE (marcus_edits_docx_directly): if the target already exists and carries
## tracked changes or comments, STOP — a rebuild would destroy them silently.
if [[ -f "$OUT" ]]; then
  python3 - "$OUT" <<'PY' || exit 3
import sys, zipfile, re
z = zipfile.ZipFile(sys.argv[1]); d = z.read("word/document.xml").decode("utf8", "replace")
ins, dele = d.count("<w:ins "), d.count("<w:del ")
com = ""
if "word/comments.xml" in z.namelist():
    com = re.sub(r"<[^>]+>", " ", z.read("word/comments.xml").decode("utf8", "replace")).strip()
if ins or dele or com:
    print(f"*** {sys.argv[1]} carries edits (ins {ins}, del {dele}, comments {len(com)} chars).")
    print("*** Sync them into the SOURCE before rebuilding. REFUSING.")
    raise SystemExit(1)
print("  preserve-gate: no tracked changes, no comments — safe to rebuild")
PY
fi

## the parameter COUNT is read back off the table, never typed, so a vintage mismatch is loud
N=$(grep -c '^| `' "$SRC")
say "source $SRC — $N parameter rows"
say "pandoc -> $OUT"
pandoc "$SRC" -o "$OUT" --resource-path=. \
  --from=markdown+pipe_tables-smart-implicit_figures --to=docx \
  || { say "pandoc failed; STOP"; exit 4; }

## ⭐ INDEPENDENT-READER GATE — pandoc wrote it, so something that is NOT pandoc must read it back.
say "verifying with an independent reader (textutil)"
TXT=$(textutil -convert txt -stdout "$OUT" 2>/dev/null)
WORDS=$(echo "$TXT" | wc -w | tr -d ' ')
[[ "${WORDS:-0}" -ge 500 ]] || { say "*** independent reader got ${WORDS:-0} words — STOP ***"; exit 5; }
echo "$TXT" | grep -q "Table A1" || { say "*** the .docx does not contain 'Table A1'; STOP ***"; exit 6; }
## and the COUNT must survive the conversion: a table truncated by pandoc is otherwise invisible
ROWS=$(echo "$TXT" | grep -c '^\s*gic_\|^\s*ais_\|^\s*antarctic_\|^\s*anto_\|^\s*gis_\|^\s*sd_\|^\s*rho_\|^\s*thermal_\|^\s*d2_')
say "independent reader: $WORDS words, $ROWS parameter rows (source has $N)"
[[ "$ROWS" -ge "$N" ]] || { say "*** the .docx lost rows in conversion ($ROWS < $N); STOP ***"; exit 7; }
say "OK — $OUT"
