#!/bin/bash
## RE-RUN EVERY PROJECTION ARM BEHIND THE GMD PAPER'S FIGURES ON LWS_MODE = :central (Marcus 2026-09-18),
## then the figures and the benchmark. Hindcast arms (FIG 1, Tables 4-5) do NOT depend on the LWS mode
## (the hindcast total uses the OBSERVED series) and are not re-run.
##
##   Ladrillo (scope_slr_fair_uncertainty.jl, ~4 min each):  7 vv markers + 3 SSPs (FaIR climate, tapped)
##                                                          + ssp126/245/585 x {spliced, raw} MAGICC climate
##   BRICK 2.0 (scope_slr_fairunc_oldbrick.jl, ~30 s each):  7 vv + 3 SSPs (FaIR) + 7 vv + ssp245/585 (MAGICC)
##   then build_l24_deliverable_doc.sh's figure + benchmark steps (NOT its docx step — the paper is
##   Marcus's docx; the documentation memo's docx is rebuilt only on request).
## ~1.5 h on the laptop. Torch verdict: not needed (single-core arms, no licence, 1.5 h).
## Run from a FROZEN copy of the drivers: do not edit julia/*.jl while this runs.
set -uo pipefail
cd "$(dirname "$0")"
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 VECLIB_MAXIMUM_THREADS=1
T=L24
LOG=outputs/log_paper_arms_lws_central_20260918.txt
J="julia --project=julia_v2"
say(){ echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG"; }
step(){ local nm="$1"; shift; say "START  $nm"
  if "$@" >> "$LOG" 2>&1; then say "OK     $nm"; else say "FAILED $nm (rc=$?)"; fi; }
: > "$LOG"
say "paper arms on LWS_MODE=:central | commit $(git rev-parse --short HEAD)"

## ---- QUARANTINE the seeded-LWS outputs this run replaces (never delete, never mix) ----
Q=outputs/quarantine/20260918_lws_seeded; mkdir -p "$Q"
TAP=_tap4p69K_V5p64m_tau800
n=0
for m in vvVL vvL vvLN vvML vvM vvHL vvH ssp126 ssp245 ssp585; do
  for k in cells paths gates draws; do f=outputs/scope_slr_fairunc_${k}_${m}_spliced_${T}${TAP}.csv; [ -f "$f" ] && mv "$f" "$Q/" && n=$((n+1)); done
  for k in cells paths draws; do f=outputs/scope_slr_fairunc_${k}_${m}_spliced_oldbrick.csv; [ -f "$f" ] && mv "$f" "$Q/" && n=$((n+1)); done
done
for s in ssp126 ssp245 ssp585; do for k in cells paths gates draws; do
  for f in outputs/scope_slr_fairunc_${k}_${s}_spliced_magiccclim_${T}${TAP}.csv outputs/scope_slr_fairunc_${k}_${s}_raw_magiccclim_${T}${TAP}.csv; do
    [ -f "$f" ] && mv "$f" "$Q/" && n=$((n+1)); done; done; done
for s in vvVL vvLN vvL vvML vvM vvHL vvH ssp245 ssp585; do for k in cells paths draws; do
  f=outputs/scope_slr_fairunc_${k}_${s}_spliced_oldbrick_magiccclim.csv; [ -f "$f" ] && mv "$f" "$Q/" && n=$((n+1)); done; done
cat > "$Q/README.md" <<EOR
# Quarantine 2026-09-18 — projection arms on the SEEDED land-water realisation

**Bug/convention:** until commit 4617723 Ladrillo's projection arms used \`lws=:seeded\` (one fixed-seed
random LWS realisation, MersenneTwister(2026)) and the BRICK 2.0 arm used get_model's own draw under
\`Random.seed!(2026)\` — two DIFFERENT realisations, +0.25 cm apart at 2100 and −0.41 at 2300. Marcus
(2026-09-18) switched both arms to \`LWS_MODE=:central\` (constant 0.3 mm/yr from 2019). See CHANGELOG
2026-09-18b and memory \`lws_central_default\`.

**Files here ($n):** the \`scope_slr_fairunc_{cells,paths,gates,draws}_*\` outputs for the 10 Ladrillo FaIR-climate
arms (7 vv + 3 SSP, tapped), the 6 Ladrillo MAGICC-climate arms, and the 19 BRICK 2.0 arms, as they stood
before the re-run. Moves are ≤ 0.44 cm on any total; medians of other components unaffected.

**Canonical replacement:** the same filenames under \`outputs/\`, regenerated by
\`run_paper_arms_lws_central_20260918.sh\` (each cells file now carries a \`provenance\` column naming the LWS
mode). Side arms NOT regenerated and still seeded: \`*_nomarker_*\`, \`*GICOLD/GICNEW*\`, \`ssp534over*\`, the
untapped \`*_spliced_L24.csv\`, \`ssp126_spliced_oldbrick_magiccclim\` (overshoot / matched-dT / ablation arcs, not
paper inputs).
EOR
say "quarantined $n seeded-LWS files to $Q"
for m in vvVL vvL vvLN vvML vvM vvHL vvH ssp126 ssp245 ssp585; do
  step "ladrillo $m (FaIR climate, tapped)" $J julia/scope_slr_fair_uncertainty.jl --tag=$T --ssp=$m --tap
done
for s in ssp126 ssp245 ssp585; do
  step "ladrillo $s MAGICC climate (spliced)" $J julia/scope_slr_fair_uncertainty.jl --tag=$T --ssp=$s --climate=magicc --tap
  step "ladrillo $s MAGICC climate (raw)"     $J julia/scope_slr_fair_uncertainty.jl --tag=$T --ssp=$s --climate=magicc --forcing=raw --tap
done
for m in vvVL vvL vvLN vvML vvM vvHL vvH; do
  step "brick2 $m (FaIR climate)" $J julia/scope_slr_fairunc_oldbrick.jl --ssp=$m
done
for s in ssp126 ssp245 ssp585; do
  step "brick2 $s (FaIR climate, ndraw 1000)" $J julia/scope_slr_fairunc_oldbrick.jl --ssp=$s --ndraw=1000
done
for s in vvVL vvLN vvL vvML vvM vvHL vvH ssp245 ssp585; do
  step "brick2 $s MAGICC climate" $J julia/scope_slr_fairunc_oldbrick.jl --ssp=$s --climate=magicc
done
say "=== arms done; figures + benchmark ==="
source ~/climate-env/bin/activate
step "vv model comparison"       python python/vv_model_comparison.py --tag=$T
step "ladrillo model comparison" python python/ladrillo_model_comparison.py --tag=$T
step "memo figures"              python python/plot_ladrillo_memo_figures.py --tag=$T
step "vv comparison figures"     python python/plot_model_comparison_components.py --tag=$T --set=vv --year=all
step "vv trajectories"           python python/plot_future_components.py --tag=$T --set=vv
step "vv gsic ladrillo-only"     python python/plot_vv_gsic_wr_vs_ladrillo.py --tag=$T --ladrillo-only
step "climate swap"              python python/plot_vv_climate_swap.py --tag=$T --year=all
step "responsiveness"            python python/plot_vv_responsiveness.py --tag=$T
step "benchmark (refresh)"       python python/bench_ladrillo.py --tag=$T
say "=== DONE ==="
