#!/bin/bash
## THE PULSE ARC RE-RUN, PART 2: the Ladrillo arms, the MAGICC-climate contrast arms and the cross-model downstream.
## Part 1 (run_vv_pulse_rerun_20261009.sh: quarantine, MAGICC stage 4, FACTS stage 5, BRICK 2.0 stage 3) must be done
## for each phase's inputs; every phase checks what it needs before starting.
## Rulings (Marcus 2026-10-09):
##   * Ladrillo L27 = "Ladrillo v1.2": the 10k subsample, the v1.1 single paleo assignment, 500 per chain = 2,000 draws,
##     PAIR_SEED 2026 -- the level vv joint arm's own draws, so the FaIR pulse arm's baseline IS that arm ([LEVEL-MATCH]).
##   * record conditioning, own-config drop, on the FaIR pulse arm; the MAGICC-climate arm on the COMMON draw set (the
##     FaIR arm's draws minus its REJECTED ones). julia/run_pulse_vv_magiccclim.sh passed 2000 PER CHAIN (8,000 draws,
##     unpaired with the 2,000-draw FaIR arm) despite a comment saying it matched; this runner uses 500 per chain.
##   * BRICK 2.0 (B20) is not conditioned on either climate (the 10-08 ruling).
## PHASES:
##   ladrillo    14 FaIR arms (7 markers x CO2 1 Gt / CH4 0.01 Gt), spliced, tapped; two at a time
##   magiccclim  28 Ladrillo + 28 BRICK 2.0 runs on MAGICC's paired pulse climate (spliced primary, raw control)
##   downstream  the cross-model table, scenario dependence, module-vs-climate, duration (+ figure), iGMST ordering,
##               the TE/OHC mechanism, the doc tables -- all in FaIRtoFrEDI/magicc_comparison
## Torch verdict: not needed -- ~4 min per Ladrillo run, single-core; the MAGICC climate files are local.
## Run from FROZEN copies (_frozen_*_20261009.jl), made at the start of each phase. Do not edit this file while it runs.
set -uo pipefail
PHASE="${1:?usage: $0 ladrillo|magiccclim|downstream}"
cd "$(dirname "$0")"
SLR=$PWD
FTF=$(cd ../FaIRtoFrEDI && pwd)
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 VECLIB_MAXIMUM_THREADS=1
T=L27
MCODES="VL L LN ML M HL H"
PY=~/miniforge3/envs/slr-refresh-2025/bin/python
J="julia --project=julia_v2"
NPAR=2                                    # concurrent Julia runs
LAD=julia/_frozen_scope_slr_pulse_vv_20261009.jl
BRK=julia/_frozen_scope_slr_pulse_vv_brick2_20261009.jl
WIDE=$FTF/magicc_comparison/processed/vv_pulse_wide_20261009
LOG=$SLR/outputs/log_vv_pulse_rerun_20261009.txt
say(){ echo "[$(date '+%m-%d %H:%M:%S')] $*" | tee -a "$LOG"; }
step(){ local nm="$1" lg="$2"; shift 2; say "START  $nm"
  if "$@" >> "$lg" 2>&1; then say "OK     $nm"; else say "FAILED $nm (rc=$?)"; echo "$nm" >> "$LOG.fails.$PHASE"; fi; }
psize(){ [[ "$1" == CO2 ]] && echo 1 || echo 0.01; }
sizetag(){ [[ "$1" == CO2 ]] && echo 1Gt || echo 0p01Gt; }
[[ "$PHASE" =~ ^(ladrillo|magiccclim|downstream)$ ]] || { echo "phase must be ladrillo|magiccclim|downstream"; exit 1; }
[[ -n "${LADRILLO_LWS_OBS_ANCHOR:-}${LADRILLO_PALEO_ASSIGNMENT:-}${LADRILLO_GIS_SHAPE:-}" ]] &&
  { echo "the v1.1 settings must come from the code defaults: unset LADRILLO_* overrides"; exit 1; }
rm -f "$LOG.fails.$PHASE"
export SLR J LAD BRK LOG PHASE
export -f say step psize sizetag

## ======================================== PHASE: ladrillo ============================================
if [[ "$PHASE" == ladrillo ]]; then
  cp julia/scope_slr_pulse_vv.jl "$LAD"
  one(){ local M=$1 S=$2
    step "Ladrillo $T vv$M $S (FaIR, conditioned)" /dev/null bash -c "$J $LAD --marker=$M --specie=$S --pulse-size=$(psize $S) \
      --tap --tag=$T > logs/lad_${M}_${S}.log 2>&1"; }
  export -f one; export T
  for M in $MCODES; do for S in CO2 CH4; do echo "$M $S"; done; done | xargs -P $NPAR -L 1 bash -c 'one $0 $1'
  say "ladrillo phase done, $(cat "$LOG.fails.ladrillo" 2>/dev/null | wc -l | tr -d ' ') failures"; exit 0
fi

## ======================================== PHASE: magiccclim ==========================================
if [[ "$PHASE" == magiccclim ]]; then
  for S in CO2 CH4; do [[ -f "$WIDE/gates_$S.csv" ]] || { say "missing $WIDE/gates_$S.csv: MAGICC phase not done. STOP"; exit 1; }; done
  for M in $MCODES; do for S in CO2 CH4; do
    f=outputs/pulse_ladrillo_gates_vv${M}_${S}_$(sizetag $S)_2030_spliced_${T}_tap4p69K_V5p64m_tau800.csv
    [[ -f "$f" ]] || { say "missing $f: the FaIR Ladrillo arm must run first (common draw set). STOP"; exit 1; }; done; done
  cp julia/scope_slr_pulse_vv.jl "$LAD"
  cmp -s julia/scope_slr_pulse_vv_brick2.jl "$BRK" || cp julia/scope_slr_pulse_vv_brick2.jl "$BRK"
  lad(){ local M=$1 S=$2 F=$3
    step "Ladrillo $T vv$M $S MAGICC climate ($F)" /dev/null bash -c "$J $LAD --marker=$M --specie=$S --pulse-size=$(psize $S) \
      --climate=magicc --forcing=$F --tap --tag=$T > outputs/log_pulse_magiccclim_vv${M}_${S}_${F}.txt 2>&1"; }
  brk(){ local M=$1 S=$2 F=$3
    step "BRICK 2.0 vv$M $S MAGICC climate ($F)" /dev/null bash -c "$J $BRK --marker=$M --specie=$S --pulse-size=$(psize $S) \
      --climate=magicc --forcing=$F --ndraw=2000 --tag=B20 > outputs/log_pulse_brick2_magiccclim_vv${M}_${S}_${F}.txt 2>&1"; }
  export -f lad brk; export T
  for F in spliced raw; do for M in $MCODES; do for S in CO2 CH4; do echo "lad $M $S $F"; echo "brk $M $S $F"; done; done; done |
    xargs -P $NPAR -L 1 bash -c '$0 $1 $2 $3'
  say "magiccclim phase done, $(cat "$LOG.fails.magiccclim" 2>/dev/null | wc -l | tr -d ' ') failures"; exit 0
fi

## ======================================== PHASE: downstream ==========================================
if [[ "$PHASE" == downstream ]]; then
  lg=$SLR/outputs/log_vvp_downstream.txt; : > "$lg"
  d(){ local nm="$1"; shift; step "$nm" "$lg" bash -c "cd '$FTF' && $PY $*"; }
  d "cross-model table"            magicc_comparison/build_stage4_crossmodel_table.py
  d "scenario dependence 2300"     magicc_comparison/diag_scenario_dependence_2300.py
  for m in ladrillo brick2; do for S in CO2 CH4; do
    d "module vs climate $m $S"    magicc_comparison/diag_magiccclim_module_vs_climate.py --module $m --specie $S; done; done
  d "pulse duration"               magicc_comparison/pulse_duration_vv.py
  d "pulse duration figures"       magicc_comparison/fig_pulse_duration_vv.py
  d "iGMST ordering"               magicc_comparison/diag_igmst_ordering_vv.py
  d "TE/OHC mechanism"             magicc_comparison/diag_te_ohc_mechanism_vv.py
  d "doc tables"                   magicc_comparison/build_pulse_doc_tables.py
  say "downstream phase done, $(cat "$LOG.fails.downstream" 2>/dev/null | wc -l | tr -d ' ') failures"; exit 0
fi
