"""10-01 edit set G (part 1): mechanical fixes, internal wording, back-matter sections, figure order.
Tracked by Claude, w:date 2026-10-01T00:00:00Z (distinct from earlier rounds)."""
import sys
sys.path.insert(0, "/private/tmp/claude-501/-Users-MarcusMarcus-Documents-2026-CodeProjects-FaIRtoFrEDI/e88c7db1-5ed3-4ee0-bbf2-08bb6c77ecb6/scratchpad/v1001")
from trackedit import Doc
d = Doc(sys.argv[1] + "/word/document.xml")

# typo / citation
d.replace("the Greenland peripher not included in Ladrillo,", "the Greenland periphery (neither included in Ladrillo),", "typo")
d.replace("Leach et al., 2021; Smith et al., 2024)", "Leach et al., 2021; Smith et al., 2024; Smith, 2026)",
          "Smith et al. 2024 is the v1.4.1 paper; the 1.6.0 calibration data is Smith (2026)")
# unsupported claims (no per-block output exists)
d.replace(" in the short-timescale regional block", "", "no per-block regrowth output; regrowth is measured for all glaciers")
d.replace(" This block dominates the glacier contribution in both the hindcast and the projections.", "",
          "no per-block contribution output; Table A1's committed-loss scale is larger for FASTG (0.151 m) than SLOWG (0.131 m)")
# internal wording
d.replace("(their posterior width equals their prior width in every calibration that sampled them)",
          "(when sampled, their posterior width equals their prior width)", "internal-process wording")
d.replace("accepted on the deliverable-level criterion:", "accepted for projection use:", "internal wording")
d.insert_after("98th percentiles of ", "the ice-flow constant f₀", "code name in running text")
d.replace_after("98th percentiles of ", "ais_iceflow0", "", "code name in running text")
d.insert_after("dominated by the DAIS fast-dynamics rate ", "λ", "code name in running text")
d.replace_after("dominated by the DAIS fast-dynamics rate ", "antarctic_lambda", "", "code name in running text")
d.replace(" The prior column is generated by the calibrator itself from the distributions it scores, not transcribed.", "",
          "internal-process wording")
d.replace("; SLOWG = SLOWP and FASTG = FAST in the code", "", "code naming belongs in the code docs")
d.replace("Glacier scope and ledger terms (hindcast-target constructs)", "Glacier hindcast-target term", "internal wording")
d.replace("form; sha256[:16] ", "form; SHA-256 prefix ", "code syntax")
# figure order: FIG 5 was first cited before FIG 1
d.replace("is in equilibrium with (FIG 5).", "is in equilibrium with (see Future Projections).",
          "GMD numbers figures in order of first citation; FIG 5 was cited before FIG 1")

# title page: corresponding author (Marcus 10-01)
d.insert_para("Tony E Wong, School of Mathematical Sciences", "Correspondence: Marcus C. Sarofim (msarofim@gmail.com)",
              before=False, why="GMD requires a corresponding author")
# back matter (Copernicus order: ... Author contributions, Competing interests, Acknowledgements, Financial support)
d.insert_para("Competing interests.", "Author contributions. ", before=True, why="mandatory GMD section (skeleton)")
d.insert_para("Competing interests.", "MCS: [to be completed]. TEW: [to be completed].", before=True, why="skeleton")
d.insert_para("The authors would like to thank Alexander Nauels", "This research has been supported by the Wellcome Trust.",
              before=False, why="Marcus 10-01")
d.insert_para("The authors would like to thank Alexander Nauels", "Financial support. ", before=False, why="Copernicus section")
d.save()
for o, n, w in d.log: print(f"- {o[:55]!r} -> {n[:60]!r}")
print(len(d.log), "edits")
