"""Round 3 (2026-09-19): Appendix A (Table A1) inserted before References as a tracked change."""
from redline import *
import re

x = load()
t = open("tbl/word/document.xml").read()
tbl = re.search(r"<w:tbl>.*?</w:tbl>", t, re.S).group(0)
cap = re.search(r"<w:p\b[^>]*>(?:(?!</w:p>).)*Table A1(?:(?!</w:p>).)*</w:p>", t, re.S).group(0)

def track_para(p):
    """Mark an existing paragraph (from the pandoc docx) as inserted: mark + every run wrapped."""
    mark = f'<w:ins w:id="{nid()}" w:author="{AUTHOR}" w:date="{DATE}"/>'
    if "<w:pPr>" in p:
        if "<w:rPr>" in p.split("</w:pPr>")[0]:
            p = p.replace("<w:rPr>", f"<w:rPr>{mark}", 1)
        else:
            p = p.replace("</w:pPr>", f"<w:rPr>{mark}</w:rPr></w:pPr>", 1)
    else:
        p = re.sub(r"^(<w:p\b[^>]*>)", lambda m: m.group(1) + f"<w:pPr><w:rPr>{mark}</w:rPr></w:pPr>", p, count=1)
    p = re.sub(r"(<w:r\b[^>]*>.*?</w:r>)", lambda m: f'<w:ins w:id="{nid()}" w:author="{AUTHOR}" w:date="{DATE}">{m.group(1)}</w:ins>', p, flags=re.S)
    return p

def track_table(tb):
    def row(m):
        r = m.group(0)
        mark = f'<w:trPr><w:ins w:id="{nid()}" w:author="{AUTHOR}" w:date="{DATE}"/></w:trPr>'
        if "<w:trPr>" in r:
            r = r.replace("</w:trPr>", f'<w:ins w:id="{nid()}" w:author="{AUTHOR}" w:date="{DATE}"/></w:trPr>', 1)
        else:
            r = re.sub(r"^(<w:tr\b[^>]*>)(<w:tblPrEx>.*?</w:tblPrEx>)?", lambda mm: mm.group(1) + (mm.group(2) or "") + mark, r, count=1, flags=re.S)
        r = re.sub(r"(<w:r\b[^>]*>.*?</w:r>)", lambda mm: f'<w:ins w:id="{nid()}" w:author="{AUTHOR}" w:date="{DATE}">{mm.group(1)}</w:ins>', r, flags=re.S)
        return r
    return re.sub(r"<w:tr\b.*?</w:tr>", row, tb, flags=re.S)

heading = new_para("Appendix A: prior and posterior parameter distributions")
intro = new_para("Table A1 lists, for each of the 58 sampled parameters, the prior the calibration applies and the posterior median and 5–95% range over the 10,000 thinned draws, in the layout of Wong et al. (2017), Appendix A. The prior column is generated by the calibrator itself from the distributions it scores, not transcribed.")
block = heading + intro + track_para(cap) + track_table(tbl) + new_para("")
i = x.find(">References<"); ps = x.rfind("<w:p", 0, i)
x = x[:ps] + block + x[ps:]

x = replace_text(x, "58 parameters are sampled:", "58 parameters are sampled (priors and posteriors in Appendix A, Table A1):")
save(x); print("r4 applied")
