"""Round 4 (2026-09-19 pm): LWS text onto the constant convention; replies to Marcus's comments 0/3/7/11."""
from redline import *
x = load()
x = replace_para_text(x, "Land-water storage is not explicitly modeled",
    "Land-water storage is not explicitly modeled in either Ladrillo or BRICK. Where the total is compared with observations (FIG 1, Table 4) the observed series is added to both models' four modelled components — Frederikse et al. (2020) through 2018, then GRACE/GRACE-FO JPL mascons for 2019–2023 (land mass with the ice sheets masked, less the GlaMBIE glacier mass), with the 2023 value held constant through 2026. In projections both Ladrillo and the BRICK 2.0 comparison arm add a constant 0.30 mm yr⁻¹ from 2019 — the mean of the N(0.30, 0.18) mm yr⁻¹ annual rate that BRICK 2.0 draws stochastically — so land water contributes 8.5 cm by 2300, identically in every scenario and in both models. BRICK's land-water module is zero before 2019 and projections are referenced to 1995–2014, so the projected totals do not carry the observed 1995–2018 land-water change (0.4 cm); BRICK's convention is kept so that the two models' projection totals remain directly comparable.")
x = replace_text(x, "from BRICK 2.0's stochastic land-water module in projections; see below)",
                 "a constant 0.30 mm yr⁻¹ in projections; see below)")
x = replace_text(x, "in projections LWS follows BRICK's stochastic land-water module from 2019.",
                 "in projections LWS is a constant 0.30 mm yr⁻¹ from 2019.")
x = add_reply(x, 0, "Yes — switched 09-18 (both arms, constant 0.30 mm/yr from 2019, commit 4617723) and the figures were re-run on it; this paragraph, the framework sentence and footnote 15 now say so.")
x = add_reply(x, 3, "Because BRICK 2.0's land-water module is identically zero before its first projection year (2019) and the projections are re-referenced to 1995–2014, so nothing carries the observed 1995–2018 change into the projected total; we inherited that convention. The alternative is to splice the observed series (to 2023) and continue at 0.30 mm/yr after it, in both arms — a +0.4 to +0.6 cm level shift on every projection total, identical for both models, and one more figure re-run (~1.5 h). Physically cleaner; your call — I have not done it.")
x = add_reply(x, 7, "Yes — the in-figure title and the grey footer text duplicate the caption and the methods. Every figure driver now has a --paper mode (no title, no footer, 'Ladrillo' instead of the internal tag; the footer text goes to a sidecar .txt next to the PNG), written to figures/paper/. The six paper figures are rendered there and need re-inserting in place of these (aspect changes slightly without the footer band). One thing moves INTO a caption: FIG 2's seven off-panel elicited 5–95% ranges were listed in the footer — they are now in figures/paper/model_comparison_components_vv_L24_2100.caption.txt for the document caption.")
x = add_reply(x, 11, "Measured 09-18 (julia/diag_runtime_ladrillo_vs_brick20.jl): the numbers in this sentence are the medians over 300 draws on the same FaIR driver; per-draw cost in both models is ~85 % parameter handling, the Mimi evaluation itself is 0.78 vs 0.65 ms.")
save(x); print("r5 applied")
